# Generated by Django 2.2.7 on 2021-10-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='thumbnail')),
                ('image', models.ImageField(upload_to='blogs')),
                ('title', models.CharField(max_length=300)),
                ('thumbnail_text', models.CharField(max_length=1000)),
                ('slug', models.SlugField()),
                ('date', models.DateField(auto_now=True)),
                ('views', models.IntegerField(default=0)),
                ('par1', models.CharField(max_length=30000)),
                ('par2', models.CharField(max_length=30000)),
                ('image2', models.ImageField(blank=True, null=True, upload_to='blogs')),
                ('par3', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
    ]
