# Generated by Django 2.2.7 on 2022-09-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=300, null=True)),
                ('comment', models.TextField(max_length=1000)),
            ],
        ),
    ]
